name: Validate PR desription

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate-pr-description:
    runs-on: hip-clr-dev1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Validate PR description
        env:
          PR_DESCRIPTION: ${{ github.event.pull_request.body }}
        run: python .github/scripts/validate_pr_description.py
